In [3]:
!pip uninstall numpy -y
!pip install numpy==1.19.5
import pandas as pd
import numpy as np
!pip install sdv
from sdv.demo import load_tabular_demo

WARNING: Skipping numpy as it is not installed.
Collecting numpy==1.19.5
  Using cached numpy-1.19.5-cp39-cp39-macosx_10_9_x86_64.whl (15.6 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
sdv 0.15.0 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
sdmetrics 0.5.0 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
rdt 0.6.4 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
pyldavis 3.3.1 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
feather 0.1.2 requires numpy==1.20.2, but you have numpy 1.19.5 which is incompatible.
feather 0.1.2 requires requests==2.25.1, but you have requests 2.27.1 which is incompatible.
deepecho 0.3.0.post1 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
ctgan 0.5.1 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
copulas 0.7.0 requires numpy<2,>=1.20.0; python_version >= "3.7", but you have numpy 1.19.5 which is incompatible.
bokeh 2.4.1 requires typing-extensions>=3.10.0, but you have typing-extensions 3.7.4.3 which is incompatible.
Successfully installed numpy-1.19.5
Requirement already satisfied: sdv in /opt/anaconda3/lib/python3.9/site-packages (0.15.0)
Requirement already satisfied: ctgan<0.6,>=0.5.1 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.5.1)
Requirement already satisfied: rdt<0.7,>=0.6.2 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.6.4)
Requirement already satisfied: graphviz<1,>=0.13.2 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.20)
Requirement already satisfied: sdmetrics<0.6,>=0.5.0 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.5.0)
Requirement already satisfied: pandas<2,>=1.1.3 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (1.3.4)
Requirement already satisfied: deepecho<0.4,>=0.3.0.post1 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.3.0.post1)
Requirement already satisfied: Faker<10,>=3.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (9.9.1)
Requirement already satisfied: tqdm<5,>=4.15 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (4.62.3)
Collecting numpy<2,>=1.20.0
  Using cached numpy-1.22.4-cp39-cp39-macosx_10_14_x86_64.whl (17.7 MB)
Requirement already satisfied: copulas<0.8,>=0.7.0 in /opt/anaconda3/lib/python3.9/site-packages (from sdv) (0.7.0)
Requirement already satisfied: matplotlib<4,>=3.4.0 in /opt/anaconda3/lib/python3.9/site-packages (from copulas<0.8,>=0.7.0->sdv) (3.4.3)
Requirement already satisfied: scipy<2,>=1.5.4 in /opt/anaconda3/lib/python3.9/site-packages (from copulas<0.8,>=0.7.0->sdv) (1.7.1)
Requirement already satisfied: torch<2,>=1.8.0 in /opt/anaconda3/lib/python3.9/site-packages (from ctgan<0.6,>=0.5.1->sdv) (1.11.0)
Requirement already satisfied: packaging<22,>=20 in /opt/anaconda3/lib/python3.9/site-packages (from ctgan<0.6,>=0.5.1->sdv) (21.0)
Requirement already satisfied: scikit-learn<2,>=0.24 in /opt/anaconda3/lib/python3.9/site-packages (from ctgan<0.6,>=0.5.1->sdv) (1.0.2)
Requirement already satisfied: torchvision<1,>=0.9.0 in /opt/anaconda3/lib/python3.9/site-packages (from ctgan<0.6,>=0.5.1->sdv) (0.12.0)
Requirement already satisfied: text-unidecode==1.3 in /opt/anaconda3/lib/python3.9/site-packages (from Faker<10,>=3.0.0->sdv) (1.3)
Requirement already satisfied: python-dateutil>=2.4 in /opt/anaconda3/lib/python3.9/site-packages (from Faker<10,>=3.0.0->sdv) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib<4,>=3.4.0->copulas<0.8,>=0.7.0->sdv) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib<4,>=3.4.0->copulas<0.8,>=0.7.0->sdv) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib<4,>=3.4.0->copulas<0.8,>=0.7.0->sdv) (8.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib<4,>=3.4.0->copulas<0.8,>=0.7.0->sdv) (3.0.4)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib<4,>=3.4.0->copulas<0.8,>=0.7.0->sdv) (1.15.0)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/lib/python3.9/site-packages (from pandas<2,>=1.1.3->sdv) (2021.3)
Requirement already satisfied: pyyaml<6,>=5.4.1 in /opt/anaconda3/lib/python3.9/site-packages (from rdt<0.7,>=0.6.2->sdv) (5.4.1)
Requirement already satisfied: psutil<6,>=5.7 in /opt/anaconda3/lib/python3.9/site-packages (from rdt<0.7,>=0.6.2->sdv) (5.8.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from scikit-learn<2,>=0.24->ctgan<0.6,>=0.5.1->sdv) (2.2.0)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/lib/python3.9/site-packages (from scikit-learn<2,>=0.24->ctgan<0.6,>=0.5.1->sdv) (1.1.0)
Requirement already satisfied: pyts<0.13.0,>=0.12.0 in /opt/anaconda3/lib/python3.9/site-packages (from sdmetrics<0.6,>=0.5.0->sdv) (0.12.0)
Requirement already satisfied: numba>=0.48.0 in /opt/anaconda3/lib/python3.9/site-packages (from pyts<0.13.0,>=0.12.0->sdmetrics<0.6,>=0.5.0->sdv) (0.54.1)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.9/site-packages (from numba>=0.48.0->pyts<0.13.0,>=0.12.0->sdmetrics<0.6,>=0.5.0->sdv) (58.0.4)
  Using cached numpy-1.20.3-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
Requirement already satisfied: llvmlite<0.38,>=0.37.0rc1 in /opt/anaconda3/lib/python3.9/site-packages (from numba>=0.48.0->pyts<0.13.0,>=0.12.0->sdmetrics<0.6,>=0.5.0->sdv) (0.37.0)
Requirement already satisfied: typing-extensions in /opt/anaconda3/lib/python3.9/site-packages (from torch<2,>=1.8.0->ctgan<0.6,>=0.5.1->sdv) (3.7.4.3)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.9/site-packages (from torchvision<1,>=0.9.0->ctgan<0.6,>=0.5.1->sdv) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/anaconda3/lib/python3.9/site-packages (from requests->torchvision<1,>=0.9.0->ctgan<0.6,>=0.5.1->sdv) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests->torchvision<1,>=0.9.0->ctgan<0.6,>=0.5.1->sdv) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests->torchvision<1,>=0.9.0->ctgan<0.6,>=0.5.1->sdv) (2.10)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from requests->torchvision<1,>=0.9.0->ctgan<0.6,>=0.5.1->sdv) (2.0.4)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.20.3 which is incompatible.
feather 0.1.2 requires numpy==1.20.2, but you have numpy 1.20.3 which is incompatible.
feather 0.1.2 requires requests==2.25.1, but you have requests 2.27.1 which is incompatible.
bokeh 2.4.1 requires typing-extensions>=3.10.0, but you have typing-extensions 3.7.4.3 which is incompatible.
Successfully installed numpy-1.20.3

In [14]:
data=pd.read_csv("../data/cleaned_dataset.csv")

In [26]:
data

,Unnamed: 0,yearsofexperience,yearsatcompany,basesalary,company_AMD,company_Accenture,company_Adobe,company_Airbnb,company_Amazon,company_American Express,...,tag_truncated_others,country_Canada,country_Germany,country_US,country_United Kingdom,year_2017,year_2018,year_2019,year_2020,year_2021
0,0,1.5,1.5,107000.0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1,2,8.0,0.0,155000.0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,0,0,0
2,3,7.0,5.0,157000.0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
3,6,15.0,11.0,180000.0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
4,7,4.0,4.0,135000.0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33751,35319,6.0,4.0,147500.0,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,0
33752,35320,4.0,2.0,142000.0,0,0,0,0,0,0,...,1,0,0,1,0,0,1,0,0,0
33753,35321,10.0,1.0,155000.0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
33754,35322,2.0,2.0,146900.0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
33755,35323,8.0,4.0,194688.0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0

In [31]:
metadata=data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33756 entries, 0 to 33755
Columns: 226 entries, Unnamed: 0 to year_2021
dtypes: float64(3), int64(223)
memory usage: 58.2 MB

In [34]:
from sdv.lite import TabularPreset
model = TabularPreset(name='FAST_ML')
model.fit(data)

/opt/anaconda3/lib/python3.9/site-packages/sdv/lite/tabular.py:51: UserWarning: No metadata provided. Metadata will be automatically detected from your data. This process may not be accurate. We recommend writing metadata to ensure correct data handling.
  warnings.warn('No metadata provided. Metadata will be automatically '

In [35]:
synthetic_data = model.sample(num_rows=10000)

In [39]:
synthetic_data=synthetic_data.drop("Unnamed: 0",axis=1)

In [40]:
synthetic_data

,yearsofexperience,yearsatcompany,basesalary,company_AMD,company_Accenture,company_Adobe,company_Airbnb,company_Amazon,company_American Express,company_Apple,...,tag_truncated_others,country_Canada,country_Germany,country_US,country_United Kingdom,year_2017,year_2018,year_2019,year_2020,year_2021
0,0.000000,3.348796,83196.872732,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,0
1,1.294269,2.608107,187497.450037,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,10.606706,5.784139,221158.856592,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
3,1.108414,0.000000,229453.773583,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,10.757143,1.595124,133962.046611,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,5.280686,3.187822,221337.905103,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9996,10.919290,1.684020,160021.063180,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,1
9997,1.461040,0.000000,112232.169477,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
9998,11.143343,1.798436,206901.930089,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9999,9.518492,2.920909,214869.870023,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1

In [46]:
import statsmodels.api as sm
X = synthetic_data.drop("basesalary", axis=1)
Y = synthetic_data["basesalary"]

regression = sm.OLS(Y, X).fit()
predictions = regression.predict(data.drop(["basesalary","Unnamed: 0"],axis=1))
regression.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:             basesalary   R-squared (uncentered):                   0.951
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              2813.
Date:                Mon, 13 Jun 2022   Prob (F-statistic):                        0.00
Time:                        21:37:46   Log-Likelihood:                     -1.1912e+05
No. Observations:               10000   AIC:                                  2.384e+05
Df Residuals:                    9932   BIC:                                  2.389e+05
Df Model:                          68
Covariance Type:            nonrobust
================================================================================================================
                                                   coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
yearsofexperience                             4681.1418     79.977     58.531      0.000    4524.370    4837.914
yearsatcompany                                 205.2924    155.803      1.318      0.188    -100.113     510.698
company_AMD                                   9.405e-12   6.26e-11      0.150      0.881   -1.13e-10    1.32e-10
company_Accenture                             4.514e-11   2.73e-11      1.652      0.099   -8.42e-12    9.87e-11
company_Adobe                                -8.897e-12   6.58e-11     -0.135      0.892   -1.38e-10     1.2e-10
company_Airbnb                               -2.913e-12   5.26e-11     -0.055      0.956   -1.06e-10       1e-10
company_Amazon                               -9416.8850    964.638     -9.762      0.000   -1.13e+04   -7525.998
company_American Express                       1.61e-11   3.37e-11      0.478      0.632   -4.99e-11    8.21e-11
company_Apple                                  1.02e+04   2682.604      3.804      0.000    4944.999    1.55e+04
company_Atlassian                             4.071e-11   3.26e-11      1.248      0.212   -2.32e-11    1.05e-10
company_Autodesk                              8.533e-12   4.48e-11      0.190      0.849   -7.93e-11    9.64e-11
company_Bloomberg                             7.233e-12   3.23e-11      0.224      0.823    -5.6e-11    7.05e-11
company_Boeing                                8.594e-12    3.2e-11      0.269      0.788   -5.41e-11    7.13e-11
company_Booking.com                           1.573e-11    5.6e-11      0.281      0.779    -9.4e-11    1.25e-10
company_Box                                  -1.173e-11   4.67e-11     -0.251      0.802   -1.03e-10    7.98e-11
company_Broadcom                              -1.39e-11   3.57e-11     -0.390      0.697   -8.38e-11     5.6e-11
company_ByteDance                            -5.527e-11   4.67e-11     -1.185      0.236   -1.47e-10    3.62e-11
company_Capital One                          -3.566e-12    1.4e-11     -0.255      0.799    -3.1e-11    2.39e-11
company_Cisco                                 -373.7168   2.09e+04     -0.018      0.986   -4.14e+04    4.07e+04
company_Comcast                               1.859e-11   2.41e-11      0.771      0.440   -2.86e-11    6.58e-11
company_Cruise                                4.584e-11   7.25e-11      0.632      0.527   -9.63e-11    1.88e-10
company_Dell Technologies                    -1.872e-11   7.54e-11     -0.248      0.804   -1.67e-10    1.29e-10
company_Deloitte                             -4.136e-11   5.35e-11     -0.773      0.440   -1.46e-10    6.35e-11
company_DoorDash                              2.702e-11    4.6e-11      0.587      0.557   -6.32e-11    1.17e-10
company_Dropbox                               1.095e-11    3.8e-11      0.288      0.773   -6.35e-11    8.54e-11
company_EPAM Systems                          4.026e-11   6.68e-11      0.603      0.547   -9.06e-11    1.71e-10
company_Ernst and Young                      -6.211e-11   6.93e-11     -0.897      0.370   -1.98e-10    7.36e-11
company_Expedia                              -1.013e-11   2.26e-11     -0.449      0.654   -5.44e-11    3.41e-11
company_Facebook                              1.515e+04   1510.972     10.024      0.000    1.22e+04    1.81e+04
company_General Motors                        1.764e-11   3.52e-11      0.502      0.616   -5.13e-11    8.65e-11
company_GoDaddy                               3.945e-11   3.91e-11      1.009      0.313   -3.72e-11    1.16e-10
company_Goldman Sachs                        -3.719e-12   2.65e-11     -0.140      0.889   -5.58e-11    4.83e-11
company_Google                                4628.0941   1328.375      3.484      0.000    2024.209    7231.979
company_IBM                                  -1.084e-10   6.59e-11     -1.645      0.100   -2.38e-10    2.08e-11
company_Indeed                                6.029e-11   5.69e-11      1.059      0.290   -5.13e-11    1.72e-10
company_Instacart                            -1.679e-11   4.81e-11     -0.349      0.727   -1.11e-10    7.75e-11
company_Intel                                -2.293e-11   5.49e-11     -0.417      0.676   -1.31e-10    8.47e-11
company_Intuit                                5.954e-11   1.74e-10      0.342      0.732   -2.82e-10    4.01e-10
company_JPMorgan Chase                        -3.92e-11   6.27e-11     -0.625      0.532   -1.62e-10    8.37e-11
company_LinkedIn                              4307.1451   3.63e+04      0.119      0.906   -6.69e+04    7.55e+04
company_Lockheed Martin                       2.948e-11   4.61e-11      0.639      0.523   -6.09e-11     1.2e-10
company_Lyft                                  -4.29e-12   2.51e-11     -0.171      0.864   -5.35e-11    4.49e-11
company_Microsoft                            -2673.7772   1182.940     -2.260      0.024   -4992.579    -354.975
company_Morgan Stanley                        2.701e-11   1.99e-11      1.355      0.175   -1.21e-11    6.61e-11
company_Netflix                               3.957e-11   3.28e-11      1.208      0.227   -2.47e-11    1.04e-10
company_Northrop Grumman                       2.86e-11    3.3e-11      0.866      0.387   -3.62e-11    9.34e-11
company_Nutanix                               3.936e-11    4.1e-11      0.961      0.337   -4.09e-11     1.2e-10
company_Nvidia                                1.703e-11    2.3e-11      0.741      0.459   -2.81e-11    6.21e-11
company_Oracle                               -2.262e+04   1.48e+04     -1.527      0.127   -5.17e+04    6419.809
company_PayPal                               -9.756e-12   8.52e-12     -1.145      0.252   -2.65e-11    6.95e-12
company_Pinterest                            -3.052e-11   2.14e-11     -1.427      0.154   -7.24e-11    1.14e-11
company_Qualcomm                             -2.384e-11   2.86e-11     -0.834      0.404   -7.98e-11    3.22e-11
company_Qualtrics                            -2.018e-11   1.69e-11     -1.195      0.232   -5.33e-11    1.29e-11
company_SAP                                  -4.223e-11   3.75e-11     -1.125      0.260   -1.16e-10    3.13e-11
company_Salesforce                            3401.0968   1.01e+04      0.338      0.736   -1.63e+04    2.31e+04
company_Samsung                               1.325e-11   9.53e-12      1.391      0.164   -5.42e-12    3.19e-11
company_ServiceNow                           -5.044e-12   5.86e-12     -0.860      0.390   -1.65e-11    6.45e-12
company_Shopify                              -1.068e-12    3.7e-12     -0.289      0.773   -8.32e-12    6.18e-12
company_Snap                                  3.475e-12   2.46e-11      0.141      0.888   -4.48e-11    5.17e-11
company_Splunk                                -2.14e-12   1.36e-11     -0.157      0.875   -2.89e-11    2.46e-11
company_Spotify                              -5.723e-12   7.92e-12     -0.723      0.470   -2.12e-11    9.79e-12
company_Square                                8.942e-13   6.83e-12      0.131      0.896   -1.25e-11    1.43e-11
company_Stripe                               -5.073e-13   6.81e-12     -0.074      0.941   -1.39e-11    1.28e-11
company_T-Mobile                              2.496e-12   1.11e-11      0.225      0.822   -1.92e-11    2.42e-11
company_Tesla                                -8.378e-12   1.42e-11     -0.590      0.555   -3.62e-11    1.95e-11
company_Twilio                               -1.139e-12   2.94e-12     -0.387      0.699   -6.91e-12    4.63e-12
company_Twitter                              -6.786e-13   1.42e-11     -0.048      0.962   -2.86e-11    2.72e-11
company_Uber                                 -1.589e+04   1.81e+04     -0.876      0.381   -5.14e+04    1.97e+04
company_VMware                                        0          0        nan        nan           0           0
company_Visa                                          0          0        nan        nan           0           0
company_Walmart                                       0          0        nan        nan           0           0
company_Walmart Labs                                  0          0        nan        nan           0           0
company_Wayfair                                       0          0        nan        nan           0           0
company_Workday                                       0          0        nan        nan           0           0
company_Yahoo                                         0          0        nan        nan           0           0
company_Yelp                                          0          0        nan        nan           0           0
company_Zillow                                        0          0        nan        nan           0           0
company_eBay                                          0          0        nan        nan           0           0
level_4                                               0          0        nan        nan           0           0
level_5                                               0          0        nan        nan           0           0
level_59                                     -1.929e+04   3.62e+04     -0.532      0.594   -9.03e+04    5.18e+04
level_6                                               0          0        nan        nan           0           0
level_60                                              0          0        nan        nan           0           0
level_61                                              0          0        nan        nan           0           0
level_62                                              0          0        nan        nan           0           0
level_63                                     -1.093e+04   3.62e+04     -0.302      0.763   -8.19e+04    6.01e+04
level_64                                              0          0        nan        nan           0           0
level_65                                              0          0        nan        nan           0           0
level_66                                              0          0        nan        nan           0           0
level_67                                              0          0        nan        nan           0           0
level_7                                               0          0        nan        nan           0           0
level_Analyst                                         0          0        nan        nan           0           0
level_Associate                                       0          0        nan        nan           0           0
level_Band 7                                          0          0        nan        nan           0           0
level_Director                                        0          0        nan        nan           0           0
level_E3                                              0          0        nan        nan           0           0
level_E4                                              0          0        nan        nan           0           0
level_E5                                       -76.6718   1.82e+04     -0.004      0.997   -3.58e+04    3.56e+04
level_E6                                              0          0        nan        nan           0           0
level_Engineer                                        0          0        nan        nan           0           0
level_Grade 10                                        0          0        nan        nan           0           0
level_Grade 6                                         0          0        nan        nan           0           0
level_Grade 8                                         0          0        nan        nan           0           0
level_IC-2                                            0          0        nan        nan           0           0
level_IC-3                                            0          0        nan        nan           0           0
level_IC-4                                            0          0        nan        nan           0           0
level_IC2                                             0          0        nan        nan           0           0
level_IC3                                             0          0        nan        nan           0           0
level_IC4                                     1.271e+04   3.63e+04      0.351      0.726   -5.84e+04    8.38e+04
level_IC5                                             0          0        nan        nan           0           0
level_IC6                                             0          0        nan        nan           0           0
level_ICT2                                            0          0        nan        nan           0           0
level_ICT3                                            0          0        nan        nan           0           0
level_ICT4                                            0          0        nan        nan           0           0
level_ICT5                                            0          0        nan        nan           0           0
level_L1                                              0          0        nan        nan           0           0
level_L2                                              0          0        nan        nan           0           0
level_L3                                      -1.09e+04   3084.583     -3.534      0.000   -1.69e+04   -4855.419
level_L4                                     -2168.4939   1398.968     -1.550      0.121   -4910.755     573.767
level_L5                                      3266.8500   1318.770      2.477      0.013     681.794    5851.906
level_L5A                                             0          0        nan        nan           0           0
level_L6                                       474.3917   2076.929      0.228      0.819   -3596.810    4545.594
level_L6 SDM                                          0          0        nan        nan           0           0
level_L7                                     -2.933e+04   2.57e+04     -1.141      0.254   -7.97e+04     2.1e+04
level_L8                                              0          0        nan        nan           0           0
level_Lead MTS                                        0          0        nan        nan           0           0
level_M1                                              0          0        nan        nan           0           0
level_M2                                              0          0        nan        nan           0           0
level_MTS                                             0          0        nan        nan           0           0
level_Manager                                         0          0        nan        nan           0           0
level_P3                                              0          0        nan        nan           0           0
level_P4                                              0          0        nan        nan           0           0
level_Principal MTS                                   0          0        nan        nan           0           0
level_SDE I                                           0          0        nan        nan           0           0
level_SDE II                                          0          0        nan        nan           0           0
level_Senior                                          0          0        nan        nan           0           0
level_Senior Engineer                                 0          0        nan        nan           0           0
level_Senior MTS                                      0          0        nan        nan           0           0
level_Senior Software Engineer                4.464e+04   1.81e+04      2.462      0.014    9100.504    8.02e+04
level_Software Engineer                               0          0        nan        nan           0           0
level_Software Engineer 2                             0          0        nan        nan           0           0
level_Staff Engineer                                  0          0        nan        nan           0           0
level_Staff Software Engineer                         0          0        nan        nan           0           0
level_T4                                              0          0        nan        nan           0           0
level_T5                                              0          0        nan        nan           0           0
level_Vice President                                  0          0        nan        nan           0           0
level_other                                    960.4315    842.902      1.139      0.255    -691.827    2612.690
title_Business Analyst                                0          0        nan        nan           0           0
title_Data Scientist                          9665.9842   3997.315      2.418      0.016    1830.437    1.75e+04
title_Hardware Engineer                        392.8241   4477.247      0.088      0.930   -8383.489    9169.137
title_Human Resources                                 0          0        nan        nan           0           0
title_Management Consultant                           0          0        nan        nan           0           0
title_Marketing                                       0          0        nan        nan           0           0
title_Mechanical Engineer                             0          0        nan        nan           0           0
title_Product Designer                        1.545e+04   7572.310      2.041      0.041     611.179    3.03e+04
title_Product Manager                         7863.7416   1475.462      5.330      0.000    4971.536    1.08e+04
title_Recruiter                                       0          0        nan        nan           0           0
title_Sales                                           0          0        nan        nan           0           0
title_Software Engineer                       6450.1981    807.027      7.993      0.000    4868.262    8032.134
title_Software Engineering Manager            1.565e+04   2131.764      7.341      0.000    1.15e+04    1.98e+04
title_Solution Architect                              0          0        nan        nan           0           0
title_Technical Program Manager              -1.428e+04   7931.234     -1.800      0.072   -2.98e+04    1269.972
location_Atlanta, GA                                  0          0        nan        nan           0           0
location_Austin, TX                          -1.233e+04   5676.886     -2.173      0.030   -2.35e+04   -1206.844
location_Bellevue, WA                         1.065e+04   2.57e+04      0.414      0.679   -3.97e+04     6.1e+04
location_Berlin, BE, Germany                          0          0        nan        nan           0           0

In [47]:
predictions

0         96970.037689
1        120777.295339
2        182797.821923
3        201249.247086
4        137534.712285
             ...
33751    142463.918822
33752    146985.433713
33753    171350.738119
33754    122047.402591
33755    178405.145221
Length: 33756, dtype: float64

In [49]:
from sklearn.metrics import mean_squared_error
rmse = float(format(np.sqrt(mean_squared_error(data["basesalary"], predictions)), '.3f'))
print("\nRMSE: ", rmse)

RMSE:  33077.094